<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require("vendor/autoload.php");
require("env.php");

// A user-defined error handler function
function myErrorHandler($errno, $errstr, $errfile, $errline) {
    echo "<b>Custom error:</b> [$errno] $errstr<br>";
    echo " Error on line $errline in $errfile<br>";
}

// Set user-defined error handler function
set_error_handler("myErrorHandler");


global $wp_bearer;

$client = new GuzzleHttp\Client();

$custom_title = 'How he do that';
$content = 'How he get that way';

$post_data = [
    "title" => $custom_title,
    "content" => $content,
    "excerpt" => "Excerpt goes here",
    "status" => "publish"
];

$auth = 'Authorization: Basic '.$wp_bearer;

$response = $client->post('https://staging2.conveyancingqld.com/wp-json/wp/v2/for-you', [
    'headers' => [
        'Content-Type' => 'application/json',
        'Authorization' => 'Basic Y29yb25pc0BoZWFkc3R1ZGlvcy5jb20uYXU6cGFzc3dvcmQ3Nw=='
    ],
    'json' => $post_data,
    'timeout' => 5
]);

echo "Status is: ".$response->getStatusCode()."<p></p>";

var_dump(json_decode($response->getBody(),true));

/*

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://staging2.conveyancingqld.com//wp-json/wp/v2/for-you');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{ \"title\": \"Clown World\", \"content\" : \"Allow me to introduce myself\", \"excerpt\" : \"This is some short text\", \"status\" : \"publish\" }");

$headers = array();
$headers[] = 'Authorization: Basic Y29yb25pc0BoZWFkc3R1ZGlvcy5jb20uYXU6cGFzc3dvcmQ3Nw==';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

var_dump($result);

/*

global $wp_bearer;

$client = new GuzzleHttp\Client();

$custom_title = 'How he do that';
$content = 'How he get that way';

$post_data = [
    "title" => $custom_title,
    "content" => $content,
    "excerpt" => "Excerpt goes here",
    "status" => "publish"
];

$auth = 'Authorization: Basic '.$wp_bearer;

$response = $client->post('https://staging2.conveyancingqld.com/wp-json/wp/v2/for-you', [
    'headers' => [
        'Content-Type' => 'application/json',
        'Authorization' => 'Authorization: Basic Y29yb25pc0BoZWFkc3R1ZGlvcy5jb20uYXU6cGFzc3dvcmQ3Nw=='
    ],
    'json' => $post_data,
    'timeout' => 5
]);

echo "Status is: ".$response->getStatusCode()."<p></p>";

var_dump(json_decode($response->getBody(),true));


/*




die();

echo "Woah there soldier";

$cookie = new Enchilada();
$result = $cookie->newCustomPost('We Are Live', 'And this is our War Room');

var_dump($result);

$wp_custom = array (
    'fields' => array (
        'bannerhead' => 'Baba black sheep',
        'headline' => 'Headline Banner',
        'subheadline' => 'Subheadline Abracadabra',
        'cta_text' => 'CTA Linker',
        'cta_link' => 'Just Anything',
        'synthesia_id' => '323423432'

    )
); 

$result = $cookie->customFieldPush(155, $wp_custom);

var_dump($result);  

class Enchilada {

    

    function newCustomPost($custom_title, $content) {

        // All the globals are found in env.php which is in .gitignore so ask me for the codes otherwise this won't work, codes are on need to know basis to reduce risk - hope you understand
        $wp_bearer = 'd2h5d29udHlvdWNvbm5lY3Q6Y2N1WSAxWWhkIDdsTmkgMzdWSSB5MVlyIDYySEs=';
        
        $post_data = [
            "title" => $custom_title,
            "content" => $content,
            "excerpt" => "This is some short text",
            "status" => "publish"
        ];
        
    
        $ch = curl_init();
        
        curl_setopt($ch, CURLOPT_URL, 'https://staging2.conveyancingqld.com/wp-json/wp/v2/for-you');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($post_data));
        
        $headers = array();
        $auth = 'Authorization: Basic '.$wp_bearer;
        $headers[] = $auth;
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        
        //$id = $result['id'];
        //$json_result = json_decode($result);
        //return $json_result['link'];
        return $result;
        
    }

    function customFieldPush($id, $url_array) { // still need to add custom field values
        global $wp_bearer;
        $url = http_build_query($url_array);
        $ch = curl_init();
        
        curl_setopt($ch, CURLOPT_URL, 'https://staging2.conveyancingqld.com/wp-json/acf/v3/for-you/'.$id);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $url);
        
        $headers = array();
        $auth = 'Authorization: Basic '.$wp_bearer;
        $headers[] = 'Authorization: Basic d2h5d29udHlvdWNvbm5lY3Q6Y2N1WSAxWWhkIDdsTmkgMzdWSSB5MVlyIDYySEs=';
        $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        
        
        
        
        
    }


}
*/