<?php

$multi_link_response = '[
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=adams-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "adams-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.093Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.093Z",
        "secureShortURL": "https://showme.headstudios.com.au/adams-terminator",
        "idString": "lnk_1LHi_2n77CI",
        "shortURL": "https://showme.headstudios.com.au/adams-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "error": "Link already exists",
        "status": 409,
        "success": false
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=maxines-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "maxines-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.107Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.107Z",
        "secureShortURL": "https://showme.headstudios.com.au/maxines-terminator",
        "idString": "lnk_1LHi_2n77CK",
        "shortURL": "https://showme.headstudios.com.au/maxines-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=georges-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "georges-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.120Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.120Z",
        "secureShortURL": "https://showme.headstudios.com.au/georges-terminator",
        "idString": "lnk_1LHi_2n77CL",
        "shortURL": "https://showme.headstudios.com.au/georges-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "error": "Link already exists",
        "status": 409,
        "success": false
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=courtneys-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "courtneys-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.133Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.133Z",
        "secureShortURL": "https://showme.headstudios.com.au/courtneys-terminator",
        "idString": "lnk_1LHi_2n77CM",
        "shortURL": "https://showme.headstudios.com.au/courtneys-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=jamess-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "jamess-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.146Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.146Z",
        "secureShortURL": "https://showme.headstudios.com.au/jamess-terminator",
        "idString": "lnk_1LHi_2n77CN",
        "shortURL": "https://showme.headstudios.com.au/jamess-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=tammys-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "tammys-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.157Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.157Z",
        "secureShortURL": "https://showme.headstudios.com.au/tammys-terminator",
        "idString": "lnk_1LHi_2n77CO",
        "shortURL": "https://showme.headstudios.com.au/tammys-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=melinas-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "melinas-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.168Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.168Z",
        "secureShortURL": "https://showme.headstudios.com.au/melinas-terminator",
        "idString": "lnk_1LHi_2n77CP",
        "shortURL": "https://showme.headstudios.com.au/melinas-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=richards-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "richards-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.179Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.179Z",
        "secureShortURL": "https://showme.headstudios.com.au/richards-terminator",
        "idString": "lnk_1LHi_2n77CQ",
        "shortURL": "https://showme.headstudios.com.au/richards-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=rorys-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "rorys-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.191Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.191Z",
        "secureShortURL": "https://showme.headstudios.com.au/rorys-terminator",
        "idString": "lnk_1LHi_2n77CR",
        "shortURL": "https://showme.headstudios.com.au/rorys-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=peters-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "peters-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.203Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.203Z",
        "secureShortURL": "https://showme.headstudios.com.au/peters-terminator",
        "idString": "lnk_1LHi_2n77CS",
        "shortURL": "https://showme.headstudios.com.au/peters-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=jonzuns-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "jonzuns-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.214Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.214Z",
        "secureShortURL": "https://showme.headstudios.com.au/jonzuns-terminator",
        "idString": "lnk_1LHi_2n77CT",
        "shortURL": "https://showme.headstudios.com.au/jonzuns-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=fionas-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "fionas-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.226Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.226Z",
        "secureShortURL": "https://showme.headstudios.com.au/fionas-terminator",
        "idString": "lnk_1LHi_2n77CU",
        "shortURL": "https://showme.headstudios.com.au/fionas-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=imogens-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "imogens-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.239Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.239Z",
        "secureShortURL": "https://showme.headstudios.com.au/imogens-terminator",
        "idString": "lnk_1LHi_2n77CV",
        "shortURL": "https://showme.headstudios.com.au/imogens-terminator",
        "duplicate": false,
        "success": true
    },
    {
        "clicksLimit": null,
        "icon": null,
        "title": null,
        "iphoneURL": null,
        "androidURL": null,
        "expiresAt": null,
        "expiredURL": null,
        "source": "api",
        "splitURL": null,
        "splitPercent": null,
        "integrationGA": null,
        "integrationGTM": null,
        "integrationFB": null,
        "integrationAdroll": null,
        "originalURL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/?name=michaels-terminator",
        "DomainId": 421680,
        "archived": false,
        "path": "michaels-terminator",
        "cloaking": false,
        "redirectType": null,
        "createdAt": "2022-06-24T06:35:27.254Z",
        "OwnerId": 458432,
        "updatedAt": "2022-06-24T06:35:27.254Z",
        "secureShortURL": "https://showme.headstudios.com.au/michaels-terminator",
        "idString": "lnk_1LHi_2n77CW",
        "shortURL": "https://showme.headstudios.com.au/michaels-terminator",
        "duplicate": false,
        "success": true
    }
]';

$input_token = '{
    "0": {
        "displayName": "Adam",
        "path": "adams-terminator"
    },
    "1": {
        "ID": "recfxg2gyjjHdb8t6",
        "Name": "Adam  Scott",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Greg",
        "path": "gregs-terminator"
    },
    "2": {
        "ID": "recOoVKL01n7BKtIX",
        "Name": "Greg  Brewster",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Maxine",
        "path": "maxines-terminator"
    },
    "3": {
        "ID": "recCOirpr3oQ7Wcce",
        "Name": "Maxine Pemble",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "George",
        "path": "georges-terminator"
    },
    "4": {
        "ID": "recW8Del9vgmSwvtj",
        "Name": "George  Savva",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Greg",
        "path": "gregs-terminator"
    },
    "5": {
        "ID": "recYI0ceAZkBQNHdS",
        "Name": "Greg  McKinley",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Courtney",
        "path": "courtneys-terminator"
    },
    "6": {
        "ID": "rec69N1WoIfzlUXJ1",
        "Name": "Courtney  Rumble",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "James",
        "path": "jamess-terminator"
    },
    "7": {
        "ID": "recZcTBdD9lYaKbhS",
        "Name": "James  Harvey",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Tammy",
        "path": "tammys-terminator"
    },
    "8": {
        "ID": "rec9qtv4uWW3IR5cR",
        "Name": "Tammy Stringer",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Melina",
        "path": "melinas-terminator"
    },
    "9": {
        "ID": "recXpbdiYnzJkPMLC",
        "Name": "Melina Brawley",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Richard",
        "path": "richards-terminator"
    },
    "10": {
        "ID": "recoiUCZq5x70Ebo6",
        "Name": "Richard Whiteley",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Rory",
        "path": "rorys-terminator"
    },
    "11": {
        "ID": "rec2VnfgbyosRz4Py",
        "Name": "Rory McElwee",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Peter",
        "path": "peters-terminator"
    },
    "12": {
        "ID": "recUV9XFREY8USsCM",
        "Name": "Peter  Darcy",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Jonzun",
        "path": "jonzuns-terminator"
    },
    "13": {
        "ID": "recT0i6B1deicfQ3A",
        "Name": "Jonzun Lee",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Fiona",
        "path": "fionas-terminator"
    },
    "14": {
        "ID": "reckFTxKxzqWHxH4t",
        "Name": "Fiona  Greene",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Imogen",
        "path": "imogens-terminator"
    },
    "15": {
        "ID": "recjDpkCmvVQcq3hj",
        "Name": "Imogen Callister",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg",
        "displayName": "Michael",
        "path": "michaels-terminator"
    },
    "16": {
        "ID": "recb7oQIaUx3573lS",
        "Name": "Michael Mills",
        "URL": "https://headstudios.com.au/for_you/sales-terminator-army-generator/",
        "Shortlink": "",
        "LinkID": "",
        "image": "https://dl.airtable.com/.attachments/faaeedf7c2d0b7bd0bd3334102037634/f5036edf/andrew_coronis.jpg"
    }
}';

$link_response = json_decode($multi_link_response, true);
$input = json_decode($input_token,true);
echo '<pre>';
echo 'Link response is: ';
var_dump($link_response);
foreach($link_response as $response) {
    echo "<br />response[path] is ".$response['path'];
    $key = array_search($response['path'], array_column($input, 'path'));

    echo " and Input[key][path] is: ".$input[$key]['path'].'</br>';
    
    if($key) {
    echo "Your key for ".$response['path']." is: ".$key;
    $input[$key]['originalURL'] = $response['originalURL'];
    $input[$key]['secureShortURL'] = $response['secureShortURL'];
    }
}
echo 'Input is: ';
var_dump($input);
echo '</pre>';